import Head from 'next/head'
import useIndex from '../data/hooks/pages/useIndex.page'
import PostList from '../ui/components/PostList/PostList'


export default function Home() {

  const { posts } = useIndex()

  return (
    <div>
      <Head>
        <title>Treinablog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="favicon.ico" />
      </Head>

      <main>
        <PostList posts={posts}/>
      </main>
    </div>
  )
}
